<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    public function run(): void
    {
        $currencies = [
            ['code' => 'USD', 'name' => 'US Dollar'],
            ['code' => 'EUR', 'name' => 'Euro'],
            ['code' => 'GBP', 'name' => 'British Pound Sterling'],
            ['code' => 'CHF', 'name' => 'Swiss Franc'],
        ];

        foreach ($currencies as $currency) {
            Currency::create($currency);
        }
    }
}

//$currencies = [
//    ['code' => 'PLN', 'name' => 'Zloty'],
//    ['code' => 'ZWL', 'name' => 'Zimbabwe Dollar'],
//    ['code' => 'ZMW', 'name' => 'Zambian Kwacha'],
//    ['code' => 'CNY', 'name' => 'Yuan Renminbi'],
//    ['code' => 'JPY', 'name' => 'Yen'],
//    ['code' => 'YER', 'name' => 'Yemeni Rial'],
//    ['code' => 'KRW', 'name' => 'Won'],
//    ['code' => 'CHW', 'name' => 'WIR Franc'],
//    ['code' => 'CHE', 'name' => 'WIR Euro'],
//    ['code' => 'VUV', 'name' => 'Vatu'],
//    ['code' => 'UZS', 'name' => 'Uzbekistan Sum'],
//    ['code' => 'USN', 'name' => 'US Dollar (Next day)'],
//    ['code' => 'USD', 'name' => 'US Dollar'],
//    ['code' => 'UYI', 'name' => 'Uruguay Peso en Unidades Indexadas (URUIURUI)'],
//    ['code' => 'COU', 'name' => 'Unidad de Valor Real'],
//    ['code' => 'CLF', 'name' => 'Unidad de Fomento'],
//    ['code' => 'UGX', 'name' => 'Uganda Shilling'],
//    ['code' => 'AED', 'name' => 'UAE Dirham'],
//    ['code' => 'TMT', 'name' => 'Turkmenistan New Manat'],
//    ['code' => 'TRY', 'name' => 'Turkish Lira'],
//    ['code' => 'TND', 'name' => 'Tunisian Dinar'],
//    ['code' => 'MNT', 'name' => 'Tugrik'],
//    ['code' => 'TTD', 'name' => 'Trinidad and Tobago Dollar'],
//    ['code' => 'KZT', 'name' => 'Tenge'],
//    ['code' => 'TZS', 'name' => 'Tanzanian Shilling'],
//    ['code' => 'WST', 'name' => 'Tala'],
//    ['code' => 'BDT', 'name' => 'Taka'],
//    ['code' => 'SYP', 'name' => 'Syrian Pound'],
//    ['code' => 'CHF', 'name' => 'Swiss Franc'],
//    ['code' => 'SEK', 'name' => 'Swedish Krona'],
//    ['code' => 'SRD', 'name' => 'Surinam Dollar'],
//    ['code' => 'SDG', 'name' => 'Sudanese Pound'],
//    ['code' => 'XSU', 'name' => 'Sucre'],
//    ['code' => 'LKR', 'name' => 'Sri Lanka Rupee'],
//    ['code' => 'SSP', 'name' => 'South Sudanese Pound'],
//    ['code' => 'TJS', 'name' => 'Somoni'],
//    ['code' => 'SOS', 'name' => 'Somali Shilling'],
//    ['code' => 'KGS', 'name' => 'Som'],
//    ['code' => 'SBD', 'name' => 'Solomon Islands Dollar'],
//    ['code' => 'SGD', 'name' => 'Singapore Dollar'],
//    ['code' => 'SCR', 'name' => 'Seychelles Rupee'],
//    ['code' => 'RSD', 'name' => 'Serbian Dinar'],
//    ['code' => 'XDR', 'name' => 'SDR (Special Drawing Right)'],
//    ['code' => 'SAR', 'name' => 'Saudi Riyal'],
//    ['code' => 'SHP', 'name' => 'Saint Helena Pound'],
//    ['code' => 'RWF', 'name' => 'Rwanda Franc'],
//    ['code' => 'RUB', 'name' => 'Russian Ruble'],
//    ['code' => 'IDR', 'name' => 'Rupiah'],
//    ['code' => 'MVR', 'name' => 'Rufiyaa'],
//    ['code' => 'RON', 'name' => 'Romanian Leu'],
//    ['code' => 'KHR', 'name' => 'Riel'],
//    ['code' => 'OMR', 'name' => 'Rial Omani'],
//    ['code' => 'ZAR', 'name' => 'Rand'],
//    ['code' => 'GTQ', 'name' => 'Quetzal'],
//    ['code' => 'QAR', 'name' => 'Qatari Rial'],
//    ['code' => 'BWP', 'name' => 'Pula'],
//    ['code' => 'GBP', 'name' => 'Pound Sterling'],
//    ['code' => 'PHP', 'name' => 'Philippine Peso'],
//    ['code' => 'UYU', 'name' => 'Peso Uruguayo'],
//    ['code' => 'CUC', 'name' => 'Peso Convertible'],
//    ['code' => 'TOP', 'name' => 'Pa’anga'],
//    ['code' => 'MOP', 'name' => 'Pataca'],
//    ['code' => 'PKR', 'name' => 'Pakistan Rupee'],
//    ['code' => 'MRU', 'name' => 'Ouguiya'],
//    ['code' => 'PEN', 'name' => 'Nuevo Sol'],
//    ['code' => 'NOK', 'name' => 'Norwegian Krone'],
//    ['code' => 'KPW', 'name' => 'North Korean Won'],
//    ['code' => 'BTN', 'name' => 'Ngultrum'],
//    ['code' => 'NZD', 'name' => 'New Zealand Dollar'],
//    ['code' => 'TWD', 'name' => 'New Taiwan Dollar'],
//    ['code' => 'ILS', 'name' => 'New Israeli Sheqel'],
//    ['code' => 'ANG', 'name' => 'Netherlands Antillean Guilder'],
//    ['code' => 'NPR', 'name' => 'Nepalese Rupee'],
//    ['code' => 'NAD', 'name' => 'Namibia Dollar'],
//    ['code' => 'ERN', 'name' => 'Nakfa'],
//    ['code' => 'NGN', 'name' => 'Naira'],
//    ['code' => 'BOV', 'name' => 'Mvdol'],
//    ['code' => 'MZN', 'name' => 'Mozambique Metical'],
//    ['code' => 'MAD', 'name' => 'Moroccan Dirham'],
//    ['code' => 'MDL', 'name' => 'Moldovan Leu'],
//    ['code' => 'MXV', 'name' => 'Mexican Unidad de Inversion (UDI)'],
//    ['code' => 'MXN', 'name' => 'Mexican Peso'],
//    ['code' => 'MUR', 'name' => 'Mauritius Rupee'],
//    ['code' => 'MYR', 'name' => 'Malaysian Ringgit'],
//    ['code' => 'MGA', 'name' => 'Malagasy Ariary'],
//    ['code' => 'LSL', 'name' => 'Loti'],
//    ['code' => 'SZL', 'name' => 'Lilangeni'],
//    ['code' => 'LYD', 'name' => 'Libyan Dinar'],
//    ['code' => 'LRD', 'name' => 'Liberian Dollar'],
//    ['code' => 'SLE', 'name' => 'Leone'],
//    ['code' => 'HNL', 'name' => 'Lempira'],
//    ['code' => 'ALL', 'name' => 'Lek'],
//    ['code' => 'LBP', 'name' => 'Lebanese Pound'],
//    ['code' => 'GEL', 'name' => 'Lari'],
//    ['code' => 'MMK', 'name' => 'Kyat'],
//    ['code' => 'AOA', 'name' => 'Kwanza'],
//    ['code' => 'MWK', 'name' => 'Kwacha'],
//    ['code' => 'KWD', 'name' => 'Kuwaiti Dinar'],
//    ['code' => 'LAK', 'name' => 'Kip'],
//    ['code' => 'PGK', 'name' => 'Kina'],
//    ['code' => 'KES', 'name' => 'Kenyan Shilling'],
//    ['code' => 'JOD', 'name' => 'Jordanian Dinar'],
//    ['code' => 'JMD', 'name' => 'Jamaican Dollar'],
//    ['code' => 'IQD', 'name' => 'Iraqi Dinar'],
//    ['code' => 'IRR', 'name' => 'Iranian Rial'],
//    ['code' => 'INR', 'name' => 'Indian Rupee'],
//    ['code' => 'ISK', 'name' => 'Iceland Krona'],
//    ['code' => 'UAH', 'name' => 'Hryvnia'],
//    ['code' => 'HKD', 'name' => 'Hong Kong Dollar'],
//    ['code' => 'GYD', 'name' => 'Guyana Dollar'],
//    ['code' => 'GNF', 'name' => 'Guinea Franc'],
//    ['code' => 'PYG', 'name' => 'Guarani'],
//    ['code' => 'HTG', 'name' => 'Gourde'],
//    ['code' => 'GIP', 'name' => 'Gibraltar Pound'],
//    ['code' => 'GHS', 'name' => 'Ghana Cedi'],
//    ['code' => 'HUF', 'name' => 'Forint'],
//    ['code' => 'FJD', 'name' => 'Fiji Dollar'],
//    ['code' => 'FKP', 'name' => 'Falkland Islands Pound'],
//    ['code' => 'EUR', 'name' => 'Euro'],
//    ['code' => 'ETB', 'name' => 'Ethiopian Birr'],
//    ['code' => 'SVC', 'name' => 'El Salvador Colon'],
//    ['code' => 'EGP', 'name' => 'Egyptian Pound'],
//    ['code' => 'XCD', 'name' => 'East Caribbean Dollar'],
//    ['code' => 'VND', 'name' => 'Dong'],
//    ['code' => 'DOP', 'name' => 'Dominican Peso'],
//    ['code' => 'STN', 'name' => 'Dobra'],
//    ['code' => 'DJF', 'name' => 'Djibouti Franc'],
//    ['code' => 'MKD', 'name' => 'Denar'],
//    ['code' => 'DKK', 'name' => 'Danish Krone'],
//    ['code' => 'GMD', 'name' => 'Dalasi'],
//    ['code' => 'CZK', 'name' => 'Czech Koruna'],
//    ['code' => 'CUP', 'name' => 'Cuban Peso'],
//    ['code' => 'CRC', 'name' => 'Costa Rican Colon'],
//    ['code' => 'NIO', 'name' => 'Cordoba Oro'],
//    ['code' => 'BAM', 'name' => 'Convertible Mark'],
//    ['code' => 'CDF', 'name' => 'Congolese Franc'],
//    ['code' => 'KMF', 'name' => 'Comoro Franc'],
//    ['code' => 'COP', 'name' => 'Colombian Peso'],
//    ['code' => 'CLP', 'name' => 'Chilean Peso'],
//    ['code' => 'XPF', 'name' => 'CFP Franc'],
//    ['code' => 'XAF', 'name' => 'CFA Franc BEAC'],
//    ['code' => 'XOF', 'name' => 'CFA Franc BCEAO'],
//    ['code' => 'KYD', 'name' => 'Cayman Islands Dollar'],
//    ['code' => 'CAD', 'name' => 'Canadian Dollar'],
//    ['code' => 'CVE', 'name' => 'Cabo Verde Escudo'],
//    ['code' => 'BIF', 'name' => 'Burundi Franc'],
//    ['code' => 'BGN', 'name' => 'Bulgarian Lev'],
//    ['code' => 'BND', 'name' => 'Brunei Dollar'],
//    ['code' => 'BRL', 'name' => 'Brazilian Real'],
//    ['code' => 'BOB', 'name' => 'Boliviano'],
//    ['code' => 'VEF', 'name' => 'Bolivar'],
//    ['code' => 'VED', 'name' => 'Bolivar'],
//    ['code' => 'BMD', 'name' => 'Bermudian Dollar'],
//    ['code' => 'BZD', 'name' => 'Belize Dollar'],
//    ['code' => 'BYN', 'name' => 'Belarussian Ruble'],
//    ['code' => 'BBD', 'name' => 'Barbados Dollar'],
//    ['code' => 'PAB', 'name' => 'Balboa'],
//    ['code' => 'THB', 'name' => 'Baht'],
//    ['code' => 'BHD', 'name' => 'Bahraini Dinar'],
//    ['code' => 'BSD', 'name' => 'Bahamian Dollar'],
//    ['code' => 'AZN', 'name' => 'Azerbaijanian Manat'],
//    ['code' => 'AUD', 'name' => 'Australian Dollar'],
//    ['code' => 'AWG', 'name' => 'Aruban Florin'],
//    ['code' => 'AMD', 'name' => 'Armenian Dram'],
//    ['code' => 'ARS', 'name' => 'Argentine Peso'],
//    ['code' => 'DZD', 'name' => 'Algerian Dinar'],
//    ['code' => 'AFN', 'name' => 'Afghani'],
//    ['code' => 'XUA', 'name' => 'ADB Unit of Account'],
//];
